version: '3.5'
services:
  database:
    image: mysql:5.7
    container_name: meu-banco
    networks:
      - minha-rede
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ~/database/nest:/var/lib/mysql
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - minha-rede
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - grafana_data:/var/lib/grafana
      - C:/Users/henriquemiranda/Downloads/grafana-enterprise-9.5.1.windows-amd64/grafana-9.5.1/conf/defaults.ini:/etc/grafana/grafana.ini

  app:
    build: .
    container_name: app
    networks:
      - minha-rede
    ports:
      - '3002:3002'
    depends_on:
      - database

networks:
  minha-rede:
    driver: bridge

volumes:
  grafana_data:
